Algoritmo "Conversão de celcius para fahrenheit"
// Disciplina  :  Algoritmos I
// Professor   : Andre Coteli
// Descrição   : Converte graus celcius em fahrenheit
// Autor(a)    : Victor A. Santos,Jhonata Vinicius e Vinicius Oliveira
// Data atual  : 12/05/2020

Var
g_celcius , g_fahrenheit: real

// Seção de Declarações das variáveis

Inicio

ESCREVAL("Informe a temperatura em graus celcius: ")

LEIA(g_celcius)

g_fahrenheit <- (160 + 9 * g_celcius)/5.0)

escreval ("A temperatura convertida em Fahrenheit fica em: ",g_fahrenheit)

Fimalgoritmo
